### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by joelvinaykumar** [ameyyadav09/unsupervisedLearning#1]
All the images in the ipynb notebooks are broken & are unable to load after multiple attempts in different machines

**Comment by ameyyadav09** [comment]
@JoelVinayKumar  Can you specify in which notebook are you facing the issue.

**Comment by joelvinaykumar** [comment]
All the notebooks

**Comment by ameyyadav09** [comment]
is the issue in the local repository or it's just that you are note able to see the images in the browser. The images are rendered by a static path and thats the reason its failing. I suggest you to pull the repo to your system and have a look through. It should work for you locally.

**Comment by joelvinaykumar** [comment]
I'm unable to see in github/ google collab/ localhost as well.
